FROM node:14

WORKDIR /app

COPY ./package.json .
COPY ./package-lock.json .
# COPY .env .

RUN npm install

RUN apt update
RUN apt install nano

COPY producer.js .

CMD ["node", "producer.js"]
# CMD ["bash"]
# CMD ["node"]