version: '3'
name: 'rabbitmq_sd'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbitmq_network

  consumer:
    # build:
    #   context: consumer
    #   dockerfile: Dockerfile
    image: mateus2k2/rabbitmq_sd-consumer
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network
    stdin_open: true 
    tty: true        

  producer:
    # build:
    #   context: producer
    #   dockerfile: Dockerfile
    image: mateus2k2/rabbitmq_sd-producer
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network
    stdin_open: true 
    tty: true

networks:
  rabbitmq_network:
    driver: bridge


# docker-compose up -d
# docker-compose build

# docker tag rabbitmq_sd-consumer:latest mateus2k2/rabbitmq_sd-consumer:latest
# docker tag rabbitmq_sd-producer:latest mateus2k2/rabbitmq_sd-producer:latest

# docker push mateus2k2/rabbitmq_sd-consumer:latest
# docker push mateus2k2/rabbitmq_sd-producer:latest

